import type {
	LayoutId,
	LayoutDescriptor,
} from "../../../../shared/models/terminal-layout";

export type {
	LayoutId,
	LayoutDescriptor,
	Orientation,
	Distribution,
} from "../../../../shared/models/terminal-layout";

export const TERMINAL_LAYOUTS: Record<LayoutId, LayoutDescriptor> = {
	// ---- bucket 1 ----
	"1": {
		id: "1",
		slotCount: 1,
		orientation: "none",
		distribution: "single",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [{ gridColumn: "1 / 2", gridRow: "1 / 2" }],
	},

	// ---- bucket 2 ----
	"2-v": {
		id: "2-v",
		slotCount: 2,
		orientation: "vertical",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
		],
	},
	"2-h": {
		id: "2-h",
		slotCount: 2,
		orientation: "horizontal",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
		],
	},

	// ---- bucket 3 ----
	"3-v": {
		id: "3-v",
		slotCount: 3,
		orientation: "vertical",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr 1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 4", gridRow: "1 / 2" },
		],
	},
	"3-h": {
		id: "3-h",
		slotCount: 3,
		orientation: "horizontal",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 4" },
		],
	},
	"3-vm": {
		id: "3-vm",
		slotCount: 3,
		orientation: "vertical",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 3" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
		],
	},
	"3-hm": {
		id: "3-hm",
		slotCount: 3,
		orientation: "horizontal",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 3", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
		],
	},

	// ---- bucket 4 ----
	"4-v": {
		id: "4-v",
		slotCount: 4,
		orientation: "vertical",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr 1fr 1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 4", gridRow: "1 / 2" },
			{ gridColumn: "4 / 5", gridRow: "1 / 2" },
		],
	},
	"4-h": {
		id: "4-h",
		slotCount: 4,
		orientation: "horizontal",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 4" },
			{ gridColumn: "1 / 2", gridRow: "4 / 5" },
		],
	},
	"4-vm": {
		id: "4-vm",
		slotCount: 4,
		orientation: "vertical",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 4" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "3 / 4" },
		],
	},
	"4-hm": {
		id: "4-hm",
		slotCount: 4,
		orientation: "horizontal",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "1fr 1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 4", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 4", gridRow: "2 / 3" },
		],
	},
	"4-grid": {
		id: "4-grid",
		slotCount: 4,
		orientation: "none",
		distribution: "grid",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr",
		gridTemplateRows: "1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
		],
	},

	// ---- bucket 5 ----
	"5-v": {
		id: "5-v",
		slotCount: 5,
		orientation: "vertical",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 4", gridRow: "1 / 2" },
			{ gridColumn: "4 / 5", gridRow: "1 / 2" },
			{ gridColumn: "5 / 6", gridRow: "1 / 2" },
		],
	},
	"5-h": {
		id: "5-h",
		slotCount: 5,
		orientation: "horizontal",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 4" },
			{ gridColumn: "1 / 2", gridRow: "4 / 5" },
			{ gridColumn: "1 / 2", gridRow: "5 / 6" },
		],
	},
	"5-vm": {
		id: "5-vm",
		slotCount: 5,
		orientation: "vertical",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 5" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "3 / 4" },
			{ gridColumn: "2 / 3", gridRow: "4 / 5" },
		],
	},
	"5-hm": {
		id: "5-hm",
		slotCount: 5,
		orientation: "horizontal",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "1fr 1fr 1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 5", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 4", gridRow: "2 / 3" },
			{ gridColumn: "4 / 5", gridRow: "2 / 3" },
		],
	},
	// double-master: two masters split the master region; children fill the cross axis.
	"5-vdm": {
		id: "5-vdm",
		slotCount: 5,
		orientation: "vertical",
		distribution: "double-master",
		masterSlots: 2,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 4" },
			{ gridColumn: "1 / 2", gridRow: "4 / 7" },
			{ gridColumn: "2 / 3", gridRow: "1 / 3" },
			{ gridColumn: "2 / 3", gridRow: "3 / 5" },
			{ gridColumn: "2 / 3", gridRow: "5 / 7" },
		],
	},
	"5-hdm": {
		id: "5-hdm",
		slotCount: 5,
		orientation: "horizontal",
		distribution: "double-master",
		masterSlots: 2,
		gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 4", gridRow: "1 / 2" },
			{ gridColumn: "4 / 7", gridRow: "1 / 2" },
			{ gridColumn: "1 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 5", gridRow: "2 / 3" },
			{ gridColumn: "5 / 7", gridRow: "2 / 3" },
		],
	},

	// ---- bucket 6 ----
	"6-v": {
		id: "6-v",
		slotCount: 6,
		orientation: "vertical",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr 1fr",
		gridTemplateRows: "1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 4", gridRow: "1 / 2" },
			{ gridColumn: "4 / 5", gridRow: "1 / 2" },
			{ gridColumn: "5 / 6", gridRow: "1 / 2" },
			{ gridColumn: "6 / 7", gridRow: "1 / 2" },
		],
	},
	"6-h": {
		id: "6-h",
		slotCount: 6,
		orientation: "horizontal",
		distribution: "equal",
		masterSlots: 0,
		gridTemplateColumns: "1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 4" },
			{ gridColumn: "1 / 2", gridRow: "4 / 5" },
			{ gridColumn: "1 / 2", gridRow: "5 / 6" },
			{ gridColumn: "1 / 2", gridRow: "6 / 7" },
		],
	},
	"6-vm": {
		id: "6-vm",
		slotCount: 6,
		orientation: "vertical",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 6" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "3 / 4" },
			{ gridColumn: "2 / 3", gridRow: "4 / 5" },
			{ gridColumn: "2 / 3", gridRow: "5 / 6" },
		],
	},
	"6-hm": {
		id: "6-hm",
		slotCount: 6,
		orientation: "horizontal",
		distribution: "master",
		masterSlots: 1,
		gridTemplateColumns: "1fr 1fr 1fr 1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 6", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 4", gridRow: "2 / 3" },
			{ gridColumn: "4 / 5", gridRow: "2 / 3" },
			{ gridColumn: "5 / 6", gridRow: "2 / 3" },
		],
	},
	"6-vdm": {
		id: "6-vdm",
		slotCount: 6,
		orientation: "vertical",
		distribution: "double-master",
		masterSlots: 2,
		gridTemplateColumns: "2fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 5" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "3 / 4" },
			{ gridColumn: "2 / 3", gridRow: "4 / 5" },
		],
	},
	"6-hdm": {
		id: "6-hdm",
		slotCount: 6,
		orientation: "horizontal",
		distribution: "double-master",
		masterSlots: 2,
		gridTemplateColumns: "1fr 1fr 1fr 1fr",
		gridTemplateRows: "2fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 5", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 4", gridRow: "2 / 3" },
			{ gridColumn: "4 / 5", gridRow: "2 / 3" },
		],
	},
	"6-grid23": {
		id: "6-grid23",
		slotCount: 6,
		orientation: "none",
		distribution: "grid",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr 1fr",
		gridTemplateRows: "1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "3 / 4", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "3 / 4", gridRow: "2 / 3" },
		],
	},
	"6-grid32": {
		id: "6-grid32",
		slotCount: 6,
		orientation: "none",
		distribution: "grid",
		masterSlots: 0,
		gridTemplateColumns: "1fr 1fr",
		gridTemplateRows: "1fr 1fr 1fr",
		slotPlacements: [
			{ gridColumn: "1 / 2", gridRow: "1 / 2" },
			{ gridColumn: "2 / 3", gridRow: "1 / 2" },
			{ gridColumn: "1 / 2", gridRow: "2 / 3" },
			{ gridColumn: "2 / 3", gridRow: "2 / 3" },
			{ gridColumn: "1 / 2", gridRow: "3 / 4" },
			{ gridColumn: "2 / 3", gridRow: "3 / 4" },
		],
	},
};

// Catalog order, grouped by bucket (used by the dialog gallery).
export const LAYOUT_IDS: LayoutId[] = [
	"1",
	"2-v",
	"2-h",
	"3-v",
	"3-h",
	"3-vm",
	"3-hm",
	"4-v",
	"4-h",
	"4-vm",
	"4-hm",
	"4-grid",
	"5-v",
	"5-h",
	"5-vm",
	"5-hm",
	"5-vdm",
	"5-hdm",
	"6-v",
	"6-h",
	"6-vm",
	"6-hm",
	"6-vdm",
	"6-hdm",
	"6-grid23",
	"6-grid32",
];

export function getLayout(id: LayoutId): LayoutDescriptor {
	return TERMINAL_LAYOUTS[id];
}
